export enum SubjectType {
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  TENANT_ADMIN = 'TENANT_ADMIN',
  EMPLOYEE = 'EMPLOYEE',
  DRIVER = 'DRIVER',
  CUSTOMER = 'CUSTOMER',
  SERVICE_ACCOUNT = 'SERVICE_ACCOUNT',
}
