export const GLOBAL_LOCATION_COMMAND_REPOSITORY_TOKEN = Symbol(
  'GLOBAL_LOCATION_COMMAND_REPOSITORY_TOKEN',
);

export const GLOBAL_LOCATION_QUERY_REPOSITORY_TOKEN = Symbol(
  'GLOBAL_LOCATION_QUERY_REPOSITORY_TOKEN',
);
