export const PERMISSION_QUERY_REPOSITORY_TOKEN = Symbol(
  'PERMISSION_QUERY_REPOSITORY_TOKEN',
);

export const PERMISSION_COMMAND_REPOSITORY_TOKEN = Symbol(
  'PERMISSION_COMMAND_REPOSITORY_TOKEN',
);
