export const ORGANIZATION_UNIT_COMMAND_REPOSITORY_TOKEN = Symbol(
  'ORGANIZATION_UNIT_COMMAND_REPOSITORY_TOKEN',
);

export const ORGANIZATION_UNIT_QUERY_REPOSITORY_TOKEN = Symbol(
  'ORGANIZATION_UNIT_QUERY_REPOSITORY_TOKEN',
);
