export const SUBSCRIPTION_PLAN_COMMAND_REPOSITORY = Symbol(
  'SUBSCRIPTION_PLAN_COMMAND_REPOSITORY',
);
export const SUBSCRIPTION_PLAN_QUERY_REPOSITORY = Symbol(
  'SUBSCRIPTION_PLAN_QUERY_REPOSITORY',
);
