export enum ParcelStatus {
  PROCESSING = 'PROCESSING',
  READY_FOR_DISPATCH = 'READY_FOR_DISPATCH',
  IN_TRANSIT = 'IN_TRANSIT',
  READY_FOR_COLLECTION = 'READY_FOR_COLLECTION',
  COLLECTED = 'COLLECTED',
  RETURNED = 'RETURNED',
  CANCELLED = 'CANCELLED',
}
