export enum Permission {
  // Parcels & Shipments
  CREATE_PARCEL = 'CREATE_PARCEL',
  READ_PARCEL = 'READ_PARCEL',
  UPDATE_PARCEL = 'UPDATE_PARCEL',
  DELETE_PARCEL = 'DELETE_PARCEL',
  CANCEL_PARCEL = 'CANCEL_PARCEL',
  RECEIVE_PARCEL = 'RECEIVE_PARCEL',
  DISPATCH_PARCEL = 'DISPATCH_PARCEL',
  COLLECT_PARCEL = 'COLLECT_PARCEL',

  // Shipments
  CREATE_SHIPMENT = 'CREATE_SHIPMENT',
  READ_SHIPMENT = 'READ_SHIPMENT',
  UPDATE_SHIPMENT = 'UPDATE_SHIPMENT',
  DELETE_SHIPMENT = 'DELETE_SHIPMENT',
  CANCEL_SHIPMENT = 'CANCEL_SHIPMENT',
  RETURN_SHIPMENT = 'RETURN_SHIPMENT',

  // Shipment Requests
  READ_SHIPMENT_REQUEST = 'READ_SHIPMENT_REQUEST',
  MANAGE_SHIPMENT_REQUEST = 'MANAGE_SHIPMENT_REQUEST',

  // Users & Roles
  MANAGE_USERS = 'MANAGE_USERS',
  MANAGE_ROLES = 'MANAGE_ROLES',

  // Reports
  VIEW_REPORTS = 'VIEW_REPORTS',

  // Billing
  MANAGE_BILLING = 'MANAGE_BILLING',

  // Fleet — Manifests
  CREATE_MANIFEST = 'CREATE_MANIFEST',
  READ_MANIFEST   = 'READ_MANIFEST',
  UPDATE_MANIFEST = 'UPDATE_MANIFEST',

  // Fleet — Trips
  CREATE_TRIP = 'CREATE_TRIP',
  READ_TRIP   = 'READ_TRIP',
  UPDATE_TRIP = 'UPDATE_TRIP',

  // Fleet — Vehicles
  CREATE_VEHICLE = 'CREATE_VEHICLE',
  READ_VEHICLE   = 'READ_VEHICLE',
  UPDATE_VEHICLE = 'UPDATE_VEHICLE',
  DELETE_VEHICLE = 'DELETE_VEHICLE',
}
